/* 原版地面砖 (SMB Ground.png 16x16, 烘焙1.5倍 => 24x24, scale=1) */
var GROUND_PALETTE = {
  'N': '#9c4a00',
  'O': '#ffcec5',
  'p': '#000000',
};
Object.assign(SPRITE_MAP, GROUND_PALETTE)
var SPR_GROUND = [
  'NNOOOOOOOOOOOOpNNOOOOOON',
  'NNOOOOOOOOOOOOpNNOOOOOON',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'OONNNNNNNNNNNNpOOpNNNNNp',
  'OONNNNNNNNNNNNpOOpNNNNNp',
  'OONNNNNNNNNNNNpNNppppppN',
  'OONNNNNNNNNNNNpOOOOOOOOp',
  'OONNNNNNNNNNNNpOOOOOOOOp',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'OONNNNNNNNNNNNpOONNNNNNp',
  'pppNNNNNNNNNppONNNNNNNNp',
  'pppNNNNNNNNNppONNNNNNNNp',
  'OOOpppNNNNNNppONNNNNNNNp',
  'OONOOOppppppOONNNNNNNNNp',
  'OONOOOppppppOONNNNNNNNNp',
  'OONNNNOOOOOpOONNNNNNNNNp',
  'OONNNNNNNNNpOONNNNNNNppp',
  'OONNNNNNNNNpOONNNNNNNppp',
  'NNpppppppppNOOpppppppppN',
]